### ISSUE TITLE
Add clock time to title

### ISSUE THREAD

**Issue by o2dazone** [SharkyTheWhite/palia-clock#1]
I did this modification locally to display time in the tab title, but I figure it'd be convenient for others to have access to the time with a quick glance at open browser tabs. Let me know if you'd like me to submit a PR!

**Comment by SharkyTheWhite** [comment]
Sounds like a nice idea. If you like to share your code, please do 🙂 (I also just added a license so contributions are better defined - did not expect any so fast 😄
Would be interesting to see how you added it. I need to restructure a bit soon, but at this early stage, should be easy to refactor.

**Comment by o2dazone** [comment]
I forgot to say thank you for this app, it's very helpful for someone like me who can only pop in sporadically throughout the day to tend to crops or what have.

I've created a PR here https://github.com/SharkyTheWhite/palia-clock/pull/2 - but don't feel compelled to merge it if you have a more elegant solution. Vue is not my strong suit, so I went with good ol fashioned Javascript.

**Comment by SharkyTheWhite** [comment]
Thank you for sharing your code! Glad you like it, what you describe is exactly my main use case that spawned this project in the first place 😅

I have looked at your PR and it is a valid solution. However there is a slightly more elegant way using vue watchers. Since you change the text every time we update the `realTimePST` reference, the title will be set multiple times in without it needing to actually change. With the watcher, the new title string will only be put together if the `clockText` value actually changes.

Of course this is practically a non-issue, saving about 70~80% executions of this one cheap string interpolation, but since you suggested to use an improved alternative I will close your PR and push the vue-style solution directly. Thanks again and feel invited to suggest more features 🙂

**Comment by o2dazone** [comment]
Vue watchers looks very handy! Thanks for adding this feature, and thanks for the brief Vue lesson 😄
